### ISSUE TITLE
QUESTION: Will this work with the default Cardputer Hardware ? (i.e. No LoRa Module)

### ISSUE THREAD

**Issue by Vaygrim** [nonik0/CardputerLoRaChat#1]
I'm wondering, will this work with the default ESP chip's antenna ? I don't have the external antenna module / lora module, but your chat interface is FAR better than the default ESP-NOW one is.

**Comment by Ethanol-98** [comment]
> I'm wondering, will this work with the default ESP chip's antenna ? I don't have the external antenna module / lora module, but your chat interface is FAR better than the default ESP-NOW one is.

No, you will need the LoRa Unit with Antenna (E220).

**Comment by nonik0** [comment]
No it won't, but I just pushed an update to enable ESP-NOW mode, so you can use wifi radio to communicate if you do not have LoRa module. I haven't tested it yet but I will do another release once I have done so.
