### ISSUE TITLE
Question: LoRa Status screen possible??

### ISSUE THREAD

**Issue by Seruschl** [nonik0/CardputerLoRaChat#2]
Hi and thanks for this nice tool. 

Would it be possible to implement ans status screen (or similar) to see connection details for the LoRa connection?

I am currently testing it with the ASR6501 (Atom DTU LoRaWAN Kit 868MHz) whichis giving me an one line on the signal strenght but i don't know if any gateway is around my location. So it would be great to have a more detailed status page.

**Comment by nonik0** [comment]
If you're receiving messages from a different app, I currently don't do any sort of validity checking on incoming messages. So, the app will just parse whatever bytes it gets. The signal strength indicator is drawn off the RSSI from that parsed data, so at least until I rewrite the code better, the signal strength is only valid if you are receiving valid frames from another LoRaChat app.

I figure if you are receiving frames with the LoRaWAN module, you would need to figure out the message format to decode the message from the raw bytes.
