### ISSUE TITLE
Different module

### ISSUE THREAD

**Issue by Chaoscake** [nonik0/CardputerLoRaChat#3]
Hello there,

I'm in Europe and we use 868mHz.
I don't recieve any messages or pings.
Does your apponly work with 915 mHz?

And wich channels are A B and C ?

Sorry for that question but I'm a n00b.

**Comment by nonik0** [comment]
The A, B, C channels are just within the app and are not different LoRa channels. You will only be able to send/receive messages from other Cardputers using this same app, either with LoRa or WiFi/ESP-NOW. I have not tested it with any other LoRa modules but it should work. in theory, but I am unable to debug without one.
