### ISSUE TITLE
How to use it from SD?

### ISSUE THREAD

**Issue by itJunky** [nonik0/CardputerLoRaChat#6]
Good app, but if i have only one it is useless. Want to run it from SDcard only when needed, not always. And don't wont to burn it everytime when needed.

**Comment by nonik0** [comment]
You can use [M5 Launcher](https://github.com/bmorcelli/M5Stick-Launcher) to load this or any other apps from SD. You can burn this directly from M5Burner and then just DL the bin files from M5Burner app or from the GitHub releases here to your SD.
